apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaostest
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: chaostest
            image: chaos-test:latest
            imagePullPolicy: IfNotPresent
            resources: {}
          restartPolicy: OnFailure
